### PR TITLE
fix(revm_precompiles): lock borsh semver tighter

### LINKED ISSUE #41: Borsh 0.9.2 breaks compilation of `revm_precompiles`
We hit the described change here. We should hardcode as 0.9.1 most likely.

https://github.com/near/borsh-rs/blob/master/CHANGELOG.md#092---2022-01-25

### PR DESCRIPTION
**Pull request by brockelmore**
Closes #41

### CODE REVIEW

**Review by gakonst — APPROVED** [review]
Good one

**Comment by rakita** [comment]
It seems borsh is not even used inside precompiles. Removing it, is probably fixed the problem: https://github.com/bluealloy/revm/pull/43

**Comment by gakonst** [comment]
Ha fantastic

**Comment by rakita** [comment]
remove borsh completely here: https://github.com/bluealloy/revm/pull/43

**Pull request closed without merging**
