### PR TITLE
refactor: load_account -> warm_preloaded_addresses

### LINKED ISSUE #1484: Move load account to JournaledState warm_preloaded_addresses
As JournaledState now has a warm_preloaded_addresses we dont need to preload accounts of coinbase and blockhash.
https://github.com/bluealloy/revm/blob/6df5d208a04a784fe511186cc0523d98d6e283cf/crates/revm/src/journaled_state.rs#L36

These lines should be replaced with `journal_state.warm_preloaded_addresses.insert().`
https://github.com/bluealloy/revm/blob/6df5d208a04a784fe511186cc0523d98d6e283cf/crates/revm/src/handler/mainnet/pre_execution.rs#L32-L50

### PR DESCRIPTION
**Pull request by hack3r-0m**
Closes #1484

### CODE REVIEW

**Comment by hack3r-0m** [comment]
seems like storage slot is not written while comparing it with initial account load, should it also add entry for storage slot in pre execution?

**Review by rakita — APPROVED** [review]
PR looks good, but there are few things that need to be done before this is merged.

**Comment by rakita** [comment]
Can you merge it with main.

PR https://github.com/bluealloy/revm/commit/929d4b2c825f97201e6f2a1b9fecf97a8811e2fd enabled this PR

**Comment by rakita** [comment]
Cool, it is now passing tests

**Pull request merged**
