### PR TITLE
refactor: migrate hash types from `primitive_types` to `ruint`

### PR DESCRIPTION
**Pull request by shekhirin**

### CODE REVIEW

**Comment by shekhirin** [comment]
This branch is a bit slower than `main` on stable Rust:
```console
➜  revm git:(ruint-bits) ✗ git checkout main && cargo run --package revm-test --release --bin snailtracer --quiet; git checkout ruint-bits && cargo run --package revm-test --release --bin snailtracer --quiet
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
Hello, world!
elapsed: 35.175077ms
0: 34.832375ms
1: 34.828416ms
2: 34.815541ms
3: 34.780291ms
4: 34.776208ms
5: 34.774625ms
6: 34.773583ms
7: 34.744958ms
8: 34.74225ms
9: 34.733916ms
10: 34.732791ms
11: 34.728625ms
12: 34.727625ms
13: 34.701333ms
14: 34.697458ms
15: 34.697416ms
16: 34.680541ms
17: 34.669458ms
18: 34.668125ms
19: 34.660958ms
20: 34.659083ms
21: 34.649666ms
22: 34.647875ms
23: 34.632958ms
24: 34.624791ms
end!
Switched to branch 'ruint-bits'
Your branch is up to date with 'origin/ruint-bits'.
Hello, world!
elapsed: 37.133406ms
0: 37.918041ms
1: 37.73125ms
2: 37.252291ms
3: 37.051708ms
4: 36.997083ms
5: 36.985666ms
6: 36.9675ms
7: 36.948833ms
8: 36.939333ms
9: 36.938833ms
10: 36.929458ms
11: 36.928041ms
12: 36.919291ms
13: 36.889583ms
14: 36.887791ms
15: 36.883541ms
16: 36.8785ms
17: 36.875708ms
18: 36.875166ms
19: 36.847875ms
20: 36.835125ms
21: 36.829666ms
22: 36.823583ms
23: 36.81975ms
24: 36.816333ms
end!
```

**Comment by shekhirin** [comment]
Looking at flamegraphs, it's hard to tell on MacOS what's causing the slowdown :/

---

image
main

image
ruint

**Comment by rakita** [comment]
Will take a look, btw amazing job!

**Comment by rakita** [comment]
The main difference between `U` and `H` (in this case B) types is that `U` is an array of `u64`  while `H` is an array of u8.
In that sense, hash types are very simple, they have impl `from` slices and from and into `Uint` types.

I think main culprit for this particular slowdown in this b256 try from:
https://github.com/bluealloy/revm/pull/248/files#diff-6e0cd8a086d71b468e16c86929dba4ee2f6961f5571447d09b434cabd510ccfeR6

main:
main

this:
bits

**Comment by gakonst** [comment]
@shekhirin any plans to take another pass here? else we can try to investigate

**Comment by rakita** [comment]
I am kinda started working on this. It does not make sense to have unit alias as bits, so I created revm native bits, and started porting revm there: https://github.com/bluealloy/revm/compare/rakita/native_bits

Idea is to have washed down simple `B256(pub [u8;256])` and `B160(pub [u8;160])` without a lot of addons as they are not needed.

**Comment by gakonst** [comment]
Sounds good -- cc @recmo in case any thoughts

**Comment by rakita** [comment]
Closing in favour of https://github.com/bluealloy/revm/pull/278
I added native bits that are `[u8;..]`

**Pull request closed without merging**
