### PR TITLE
feat(interpreter): expose mutable access methods on stack and memory

### PR DESCRIPTION
**Pull request by DaniPopes**

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
those are very sensitive internals,
what's the use case you have in mind here?

**Comment by DaniPopes** [comment]
We allow mutable access to everything else, we either lock everything or nothing

**Comment by mattsse** [comment]
> We allow mutable access to almost everything else

fair, not opposed to this, so defer to @rakita here

**Review by mattsse — APPROVED** [review]

**Review by rakita — APPROVED** [review]
lgtm

**Pull request merged**
