### PR TITLE
refactor(primitives): improve readability of Env.validate_tx()

### PR DESCRIPTION
**Pull request by IaroslavMazur**
The optimization comes from the fact that the respective variables are only created if they're, actually, going to be used after that (instead of being untouched due to an early return).

### CODE REVIEW

**Comment by rakita** [comment]
Would not merge this, the compiler is good enough to optimize it and not touching variables is a uncommon path.

**Comment by IaroslavMazur** [comment]
> Would not merge this, the compiler is good enough to optimize it and not touching variables is a uncommon path.

Didn't know the compiler is looking for ways to make such optimizations, as well. Good to know!
In that case, these changes don't, actually, "optimize" things.

However, I believe that the proposed changes increase code readability.

**Comment by IaroslavMazur** [comment]
> > e proposed changes increase code readability.
> 
> 
> 
> Would agree with readability, I would even remove the temp variable and use functions directly.

Should I, then, reopen the PR, removing the temporary variables?

**Comment by rakita** [comment]
> > e proposed changes increase code readability.
> 
> Would agree with readability, I would even remove the temp variable and use functions directly.

whatever is easier for you, if you want to do it in this PR just edit the title

**Comment by IaroslavMazur** [comment]
> whatever is easier for you, if you want to do it in this PR just edit the title

Done 🤝

**Review by rakita — APPROVED** [review]
lgtm!

**Pull request merged**
