### PR TITLE
feat: decode KZG trusted setup at compile time

### PR DESCRIPTION
**Pull request by DaniPopes**

### CODE REVIEW

**Comment by DaniPopes** [comment]
Hm this is pretty slow, 3.8s of const-eval straight on my machine

**Comment by rakita** [comment]
> Hm this is pretty slow, 3.8s of const-eval straight on my machine

Idea is awesome btw, but why is it so slow?

**Comment by DaniPopes** [comment]
I haven't looked into individual function performance (not sure how to do this for const-eval), but I would assume it's the combination that:
- const-eval code is interpreted without optimizations
- the file to decode is quite big
- and that we can't use `&mut`
  - every `\n` parsed iterates byte per byte, creating 2 new strings
  - every hex decode creates a new allocation for each word, then copies it into the output buffer 4000+ times, I assume this is the biggest offender

**Comment by rakita** [comment]
is PR worth adding, not sure what we gain here?

**Comment by DaniPopes** [comment]
Perf is unacceptable, will have to think about this more

**Comment by rakita** [comment]
Will close PR, we can open it again if there is a change

**Pull request closed without merging**
