### PR TITLE
feat: return Database::error

### LINKED ISSUE #309: Return more sane value that replaces `Return`
`Return` is a enum and it is internal structure, exposing it outside of revm creates not that great interface. 

There are four states that can be returns:
* `Success`: Transaction executed and it was success
* `Failure`:  Transaction executed but it failed: Check this: https://eips.ethereum.org/EIPS/eip-658
* `Error`: Transaction __not__ executed. Not enough balance in account to cover max gas consumes. 
* `ExternalError`: Transaction __not__ executed, external database error.

### PR DESCRIPTION
**Pull request by Wodann**
First step to resolve #309 

I wanted to get this under your eyes, to see what you think. This only aims to bubble up the actual `FatalExternalError`s that should not result in any gas cost.

### CODE REVIEW

**Comment by rakita** [comment]
This is not optimal as there is a lot of boilerplate code and if you are in 1000 call depth you would copy/move the DB error 1000 times. That is why I have only the simple stupid enum `Return` so I am moving only one byte and checking only one byte in the interpreter hot loop.

and is `Debug` no_std, I want revm to be able to be compiled for wasm?

**Comment by Wodann** [comment]
To make better usage of the memory, we can include the `Reason` in the `Result::Ok` to share the memory. That would allow us to remove it from the interpreter.

Also, the compiler should be smart enough to move the memory in one go for the `Reason` instead of moving it a 1000x to. If I'm not mistaken, me flagging it as `Infallible` for some paths should even result in complete optimisation of the code path. So for a `Database::Error = Infallible`, it should have no performance overhead. Benchmarks would be required to confirm that, though

**Comment by Wodann** [comment]
> and is Debug no_std, I want revm to be able to be compiled for wasm?

I can include `core::fmt::Debug` instead

**Comment by rakita** [comment]
Either way, `Reason` change should be localized, and this PR has a lot of unnecessary changes to the code.

**Comment by Wodann** [comment]
Which changes would you say are unnecessary?

**Comment by rakita** [comment]
I never intended to remove `Return` but just to cast it to something more reasonable to external call (as in from `transact`).

In the interpreter, `Return` is not made idiomatic and the reason why I didn't use `?` is there were reports of it being slower and LLVM was not optimizing it: https://agourlay.github.io/rust-performance-retrospective-part3/
 
Other than that you are adding more code to every instruction to fit `Result` pattern, it is unnecessary.

**Comment by Wodann** [comment]
I made a minimal implementation, as (I think) you envisioned. This should be a lot less intrusive

**Comment by rakita** [comment]
Change introduced here: https://github.com/bluealloy/revm/pull/334

**Pull request closed without merging**
