### PR TITLE
chore: use const blocks

### PR DESCRIPTION
**Pull request by DaniPopes**
`const {}` blocks were stabilized yesterday as part of 1.79.

I would've liked to make the instruction table `&'static` but unfortunately that requires `H: 'static` even if it's through a function pointer.

### CODE REVIEW

**Review by onbjerg — APPROVED** [review]

**Comment by DaniPopes** [comment]
Revm has no MSRV, but yes it would be a bump from 1.75 (I just tried `cargo msrv` on main b988a0f1253cd8b63a7dbf76f038758cc851bb6a)

**Review by rakita — APPROVED** [review]
lgtm!

**Comment by rakita** [comment]
Will publish a new version of revm soon, so I will merge this PR after this.

**Review by rakita — APPROVED** [review]
lgtm

**Comment by rakita** [comment]
Failed tests not related

**Pull request merged**
