### PR TITLE
`CfgEnv.chain_id` should be `u64`

### LINKED ISSUE #671: `CfgEnv.chain_id` should be `u64`
The only check done is by converting `TxEnv.chain_id` to `U256` which is redundant: https://github.com/bluealloy/revm/blob/42725351f4691c99addb1658e5deef7fb66335d0/crates/primitives/src/env.rs#L309-L314

It can be converted to `U256` directly in the `CHAINID` opcode with `U256::from`, since it's very cheap.

### PR DESCRIPTION
**Pull request by lorenzofero**
Closes #671. Let me know if I am missing something from this issue!

### CODE REVIEW

**Comment by DaniPopes** [comment]
hm actually i realized this is wrong, realistically chain id is a u64 but users should be able to set any arbitrary u256 in the EVM

**Comment by rakita** [comment]
> hm actually i realized this is wrong, realistically chain id is a u64 but users should be able to set any arbitrary u256 in the EVM

This is one of those ambiguous things where the upper limit was not specified but all the "chains" use u64, so it is a good call to use u64.

Here is a site that lists chain ids: https://chainlist.org/
from github list is here: https://github.com/DefiLlama/chainlist/blob/main/constants/chainIds.json
And biggest value is: 836542336838601

**Review by rakita — APPROVED** [review]
lgtm

**Comment by DaniPopes** [comment]
This was also enforced in Foundry, makes sense then

image

**Pull request merged**
