### PR TITLE
feat: Implement `Error` for EVMError

### PR DESCRIPTION
**Pull request by oblique**

### CODE REVIEW

**Review by rakita — COMMENTED** [review]
Intentionally left it without thiserror

**Comment by oblique** [comment]
Just curious, what was the intention?

**Comment by oblique** [comment]
Is it because of `no_std`? In that case I can manually impl the `Error` and feature gate it with `#[cfg(feature = "std")]`

**Comment by oblique** [comment]
What about now? `Error` is implemented only in case of `std` feature.

**Review by rakita — APPROVED** [review]
This looks great, lets add it as is!

**Pull request merged**
