### PR TITLE
chore: remove DatabaseWithDebugError

### PR DESCRIPTION
**Pull request by DaniPopes**
Looks unused.

### CODE REVIEW

**Comment by rakita** [comment]
It is here to be exported, usable for someone who wants a database with debug errors and does not need to redefine this trait. 

Would close this PR

**Comment by mattsse** [comment]
this looks unimplemented though, so not really useful

**Comment by DaniPopes** [comment]
if you're using it generically you would have either dbext like in foundry, or you can specify "Db<Error: Debug>" (now with rust 1.79 its even easier)

**Comment by rakita** [comment]
Convinced. Merging PR

**Review by rakita — APPROVED** [review]

**Pull request merged**
