### PR TITLE
feat: add data and into_data

### PR DESCRIPTION
**Pull request by mattsse**
adds back previous `Memory` data functions:

https://github.com/bluealloy/revm/pull/516/files

I don't fully understand if this is correct. idk what a context is or how the shared memory is laid out.

In reth inspectors we need to get the currently active memory, and I'm not sure this is still accurate:

https://github.com/paradigmxyz/reth/blob/9dd270e4e8095a4cab1d2118f8f965eec68f4db7/crates/revm/revm-inspectors/src/tracing/types.rs#L536-L537

### CODE REVIEW

**Comment by rakita** [comment]
This is not oka. `.context_memory()` should be used to fetch current call memory frame

**Comment by mattsse** [comment]
but this is exactly what this did?

and context_memory is private

**Comment by rakita** [comment]
> but this is exactly what this did?
> 
> and context_memory is private

I didn't see that `context_memory` is not public, it should be.

`into_data` would still copy the `context_memory` with `split_off`, and using `into_data` for consuming shared memory for its last context and disregarding previous ones could introduce footguns.

**Comment by mattsse** [comment]
> into_data would still copy the context_memory with split_off, and using into_data for consuming shared memory for its last context and disregarding previous ones could introduce footguns.

I see, yeah, makes sense, we need to clone that during tracing anyway,
will open another pr that makes context_memory pub then

**Comment by rakita** [comment]
> > into_data would still copy the context_memory with split_off, and using into_data for consuming shared memory for its last context and disregarding previous ones could introduce footguns.
> 
> I see, yeah, makes sense, we need to clone that during tracing anyway, will open another pr that makes context_memory pub then

Sorry if i closed this abruptly, you can make the change here or a new PR sounds okay.

**Pull request closed without merging**
