### PR TITLE
book :memo:

### PR DESCRIPTION
**Pull request by 0xJepsen**
initialization
intro + chapters
interpreter

Starts on #492

### CODE REVIEW

**Comment by rakita** [comment]
Good start!

**Comment by rakita** [comment]
Sorry for the delay, I just read it today, and it looks really nice!

**Comment by rakita** [comment]
Just changed the order of summary, will merge it as it is.

Will add later github page and link it to main README

**Comment by 0xJepsen** [comment]
Great! Glad you liked it!

**Comment by ExtremelySunnyYK** [comment]
thanks for the documentation @0xJepsen ! its really useful

**Pull request merged**
